repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Format Python (Black)
  - repo: local
    hooks:
      - id: pyright
        name: Type Check Python (pyright)
        entry: pyright
        language: node
        pass_filenames: false
        types: [python]
        additional_dependencies: ["pyright@1.1.99"]
  - repo: https://github.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        name: Lint Python (flake8)
  - repo: https://github.com/pycqa/isort
    rev: "5.8.0"
    hooks:
      - id: isort
        name: Sort Dependencies (isort)
